// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CSPACKET_HUNSERVER_CSPACKET_H_
#define FLATBUFFERS_GENERATED_CSPACKET_HUNSERVER_CSPACKET_H_

#include "flatbuffers/flatbuffers.h"

namespace HunServer {
namespace CSPacket {

struct Vec3;

struct Login;

enum PacketHeader {
  PacketHeader_NONE = 0,
  PacketHeader_Login = 1,
  PacketHeader_MIN = PacketHeader_NONE,
  PacketHeader_MAX = PacketHeader_Login
};

inline PacketHeader (&EnumValuesPacketHeader())[2] {
  static PacketHeader values[] = {
    PacketHeader_NONE,
    PacketHeader_Login
  };
  return values;
}

inline const char **EnumNamesPacketHeader() {
  static const char *names[] = {
    "NONE",
    "Login",
    nullptr
  };
  return names;
}

inline const char *EnumNamePacketHeader(PacketHeader e) {
  const size_t index = static_cast<int>(e);
  return EnumNamesPacketHeader()[index];
}

template<typename T> struct PacketHeaderTraits {
  static const PacketHeader enum_value = PacketHeader_NONE;
};

template<> struct PacketHeaderTraits<Login> {
  static const PacketHeader enum_value = PacketHeader_Login;
};

bool VerifyPacketHeader(flatbuffers::Verifier &verifier, const void *obj, PacketHeader type);
bool VerifyPacketHeaderVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3() {
    memset(this, 0, sizeof(Vec3));
  }
  Vec3(const Vec3 &_o) {
    memcpy(this, &_o, sizeof(Vec3));
  }
  Vec3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
STRUCT_END(Vec3, 12);

struct Login FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_HEADER_TYPE = 4,
    VT_HEADER = 6,
    VT_ID = 8
  };
  PacketHeader header_type() const {
    return static_cast<PacketHeader>(GetField<uint8_t>(VT_HEADER_TYPE, 0));
  }
  const void *header() const {
    return GetPointer<const void *>(VT_HEADER);
  }
  template<typename T> const T *header_as() const;
  const Login *header_as_Login() const {
    return header_type() == PacketHeader_Login ? static_cast<const Login *>(header()) : nullptr;
  }
  int16_t id() const {
    return GetField<int16_t>(VT_ID, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_HEADER_TYPE) &&
           VerifyOffset(verifier, VT_HEADER) &&
           VerifyPacketHeader(verifier, header(), header_type()) &&
           VerifyField<int16_t>(verifier, VT_ID) &&
           verifier.EndTable();
  }
};

template<> inline const Login *Login::header_as<Login>() const {
  return header_as_Login();
}

struct LoginBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_header_type(PacketHeader header_type) {
    fbb_.AddElement<uint8_t>(Login::VT_HEADER_TYPE, static_cast<uint8_t>(header_type), 0);
  }
  void add_header(flatbuffers::Offset<void> header) {
    fbb_.AddOffset(Login::VT_HEADER, header);
  }
  void add_id(int16_t id) {
    fbb_.AddElement<int16_t>(Login::VT_ID, id, 0);
  }
  LoginBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  LoginBuilder &operator=(const LoginBuilder &);
  flatbuffers::Offset<Login> Finish() {
    const auto end = fbb_.EndTable(start_, 3);
    auto o = flatbuffers::Offset<Login>(end);
    return o;
  }
};

inline flatbuffers::Offset<Login> CreateLogin(
    flatbuffers::FlatBufferBuilder &_fbb,
    PacketHeader header_type = PacketHeader_NONE,
    flatbuffers::Offset<void> header = 0,
    int16_t id = 0) {
  LoginBuilder builder_(_fbb);
  builder_.add_header(header);
  builder_.add_id(id);
  builder_.add_header_type(header_type);
  return builder_.Finish();
}

inline bool VerifyPacketHeader(flatbuffers::Verifier &verifier, const void *obj, PacketHeader type) {
  switch (type) {
    case PacketHeader_NONE: {
      return true;
    }
    case PacketHeader_Login: {
      auto ptr = reinterpret_cast<const Login *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return false;
  }
}

inline bool VerifyPacketHeaderVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPacketHeader(
        verifier,  values->Get(i), types->GetEnum<PacketHeader>(i))) {
      return false;
    }
  }
  return true;
}

inline const HunServer::CSPacket::Login *GetLogin(const void *buf) {
  return flatbuffers::GetRoot<HunServer::CSPacket::Login>(buf);
}

inline bool VerifyLoginBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<HunServer::CSPacket::Login>(nullptr);
}

inline void FinishLoginBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<HunServer::CSPacket::Login> root) {
  fbb.Finish(root);
}

}  // namespace CSPacket
}  // namespace HunServer

#endif  // FLATBUFFERS_GENERATED_CSPACKET_HUNSERVER_CSPACKET_H_
